"""Initial tables

Revision ID: af3babcfece6
Revises: b08d89de5f9d
Create Date: 2025-09-17 12:53:30.943074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3babcfece6'
down_revision: Union[str, None] = 'b08d89de5f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("ticket_logs", "id")
    op.add_column(
        "ticket_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False)
    )
    op.add_column('withdrawals', sa.Column('reason', sa.String(), nullable=True))
    op.drop_column('withdrawals', 'confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('withdrawals', 'reason')
    op.drop_column("ticket_logs", "id")
    op.add_column(
        "ticket_logs",
        sa.Column("id", sa.UUID(), primary_key=True, nullable=False)
    )
    # ### end Alembic commands ###
