"""Initial tables

Revision ID: b08d89de5f9d
Revises: bbaad00c9eb6
Create Date: 2025-09-12 12:03:50.944251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08d89de5f9d'
down_revision: Union[str, None] = 'bbaad00c9eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'payment_date')
    # ### end Alembic commands ###
