"""Initial tables

Revision ID: bbaad00c9eb6
Revises: 
Create Date: 2025-09-12 11:10:31.470697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbaad00c9eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('common_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('has_api', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('type_operator', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_table', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('next_user', sa.UUID(), nullable=True),
    sa.Column('users_validator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('users_validated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('all_users_validated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_comment', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('open_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('close_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('common_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('phone_number_code', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('sub_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('common_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opinion', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('infos', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.Column('merchant_code', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('agency_number', sa.String(), nullable=True),
    sa.Column('payment_counter', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('sub_client_id', sa.UUID(), nullable=True),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('rib_file_name', sa.String(), nullable=True),
    sa.Column('rib_file_url', sa.String(), nullable=True),
    sa.Column('rib_file_temp_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_code')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name', 'sub_client_id', name='roles_name_sub_client_id_key')
    )
    op.create_table('sub_client_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_client_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_nui', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_activity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('frequency_cycle', sa.Enum('weekly', 'monthly', name='frequencycycle'), nullable=False),
    sa.Column('frequency_week', sa.Enum('first', 'second', 'third', 'fourth', 'last', name='frequencyweek'), nullable=True),
    sa.Column('week_day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekday'), nullable=True),
    sa.Column('currency', sa.Enum('XAF', name='currency'), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sub_client_activity_id'], ['sub_client_activity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_table', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('financial_reference', sa.String(), nullable=False),
    sa.Column('credit_account', sa.UUID(), nullable=False),
    sa.Column('debit_account', sa.UUID(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credit_account'], ['payment_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account'], ['payment_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_reference')
    )
    op.create_table('policies_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source_type IN ('policy_class','permission_class')", name='ck_source_type'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'source_type', 'source_id', name='unique_role_resource')
    )
    op.create_table('user_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_client_id', sa.UUID(), nullable=False),
    sa.Column('customer_user_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("source_type IN ('role_class','policy_class','permission_class')", name='ck_source_type'),
    sa.ForeignKeyConstraint(['customer_user_id'], ['sub_client_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_user_id', 'source_type', 'source_id', name='unique_user_resource')
    )
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('attachment_file_name', sa.String(), nullable=True),
    sa.Column('attachment_file_url', sa.String(), nullable=True),
    sa.Column('attachment_file_temp_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('minimum_contribution_amount', sa.Float(), nullable=False),
    sa.Column('maximum_loan', sa.Float(), nullable=False),
    sa.Column('contribution_mandatory', sa.Boolean(), nullable=True),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('can_user_provide_withdrawal_date', sa.Boolean(), nullable=False),
    sa.Column('withdrawal_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_payment_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_account_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('debt_amount', sa.Float(), nullable=True),
    sa.Column('amount_to_endorse', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('amount_loaned_by_cycle', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cycle_id', name='guarantees_name_cycle_id_key')
    )
    op.create_table('loan_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('duration_in_day', sa.Integer(), nullable=False),
    sa.Column('interest_percentage', sa.Float(), nullable=False),
    sa.Column('is_paid_once', sa.Boolean(), nullable=True),
    sa.Column('payment_tranche', sa.Integer(), nullable=True),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'cycle_id', name='penalty_categories_title_cycle_id_key')
    )
    op.create_table('request_to_joins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('withdrawal_date', sa.Date(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cycle_id', name='request_to_joins_user_id_cycle_id_key')
    )
    op.create_table('user_cycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validator_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('validators_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag', 'cycle_id', name='validator_configs_flag_cycle_id_key')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('desired_payment_account', sa.UUID(), nullable=False),
    sa.Column('payment_account_id', sa.UUID(), nullable=True),
    sa.Column('desired_payment_mode', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.Integer(), nullable=True),
    sa.Column('amount_claimed', sa.Float(), nullable=False),
    sa.Column('amount_withdraw', sa.Float(), nullable=True),
    sa.Column('penalty_amount', sa.Float(), nullable=True),
    sa.Column('withdrawal_request_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('attachment_file_name', sa.String(), nullable=True),
    sa.Column('attachment_file_url', sa.String(), nullable=True),
    sa.Column('attachment_file_temp_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_accounts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_account_id', sa.UUID(), nullable=False),
    sa.Column('source_table', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('old_balance', sa.Float(), nullable=True),
    sa.Column('new_balance', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('debt_amount', sa.Float(), nullable=True),
    sa.Column('amount_to_endorse', sa.Float(), nullable=True),
    sa.Column('amount_loaned_by_cycle', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guarantor_id', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('guarantee_id', sa.UUID(), nullable=True),
    sa.Column('desired_operator_id', sa.UUID(), nullable=True),
    sa.Column('amount_claimed', sa.Float(), nullable=False),
    sa.Column('desired_payment_method', sa.UUID(), nullable=True),
    sa.Column('loan_config_id', sa.UUID(), nullable=False),
    sa.Column('loan_duration_day', sa.Integer(), nullable=False),
    sa.Column('interest_percentage', sa.Float(), nullable=False),
    sa.Column('guarantor_opinion', sa.Boolean(), nullable=True),
    sa.Column('refund_at_end_of_cycle', sa.Boolean(), nullable=True),
    sa.Column('cut_interest_before', sa.Boolean(), nullable=False),
    sa.Column('payment_tranche', sa.Integer(), nullable=True),
    sa.Column('file_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_temp_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('state_refund', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['desired_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['guarantee_id'], ['guarantees.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_sanction_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage_levy', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['penalty_categories.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag', 'cycle_id', name='penalties_flag_cycle_id_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_cycle_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_cycle_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('configured_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_cycle_id'], ['user_cycle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'user_cycle_id', name='user_cycle_roles_role_id_user_cycle_id_key')
    )
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('amount_given', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_interest', sa.Float(), nullable=False),
    sa.Column('total_refund_amount', sa.Float(), nullable=False),
    sa.Column('penalty_id', sa.UUID(), nullable=True),
    sa.Column('tranche_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('refund_preview_day', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_he_repaid', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['penalty_id'], ['penalty_sanction_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debt_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode', sa.Integer(), nullable=False),
    sa.Column('amount_refunded', sa.Float(), nullable=False),
    sa.Column('amount_left', sa.Float(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_table('debt_histories')
    op.drop_table('debts')
    op.drop_table('user_cycle_roles')
    op.drop_table('penalty_sanction_configs')
    op.drop_table('loan_requests')
    op.drop_table('account_movements')
    op.drop_table('withdrawals')
    op.drop_table('validator_configs')
    op.drop_table('user_cycle')
    op.drop_table('request_to_joins')
    op.drop_table('penalty_categories')
    op.drop_table('loan_configs')
    op.drop_table('guarantees')
    op.drop_table('financial_accounts')
    op.drop_table('cycle_payment_account')
    op.drop_table('cycle_configs')
    op.drop_table('contributions')
    op.drop_table('user_relations')
    op.drop_table('roles_relations')
    op.drop_table('policies_permissions')
    op.drop_table('payment_references')
    op.drop_table('cycles')
    op.drop_table('sub_client_user')
    op.drop_table('sub_client_activity')
    op.drop_table('roles')
    op.drop_table('policies')
    op.drop_table('payment_accounts')
    op.drop_table('ticket_logs')
    op.drop_table('sub_clients')
    op.drop_table('users')
    op.drop_table('type_operators')
    op.drop_table('tickets')
    op.drop_table('permissions')
    op.drop_table('operators')
    op.drop_table('logs')
    op.drop_table('clients')
    op.drop_table('activities')
    # ### end Alembic commands ###
